export const todoAppLang = {
    'app.todo.app.title': '{name}@todo',
    'app.todo.app.signout': 'Sign Out',
    'app.todo.app.create': 'Create',
    'app.todo.app.update': 'Update',
    'app.todo.app.cancel': 'Cancel',
    'app.todo.app.todos.items.add': 'New Item',
    'app.todo.app.todos.items.edit': 'Edit Item',
    'app.todo.app.todos.items.remove': 'Remove Item',
    'app.todo.app.todos.items.remove.success': 'Remove Todo item \'{name}\' successfully',
    'app.todo.app.todos.items.remove.error': 'Remove Todo item \'{name}\' failed',
    'app.todo.app.todos.items.create.success': 'Create Todo item \'{name}\' successfully',
    'app.todo.app.todos.items.create.error': 'Create Todo item \'{name}\' failed',
    'app.todo.app.todos.items.update.success': 'Update Todo item \'{name}\' successfully',
    'app.todo.app.todos.items.update.error': 'Update Todo item \'{name}\' failed',
    'app.todo.app.todos.items.empty': 'No Items',
    'app.todo.app.todos.add': 'New Todo',
    'app.todo.app.todos.edit': 'Edit Todo',
    'app.todo.app.todos.remove': 'Remove Todo',
    'app.todo.app.todos.remove.success': 'Remove Todo \'{name}\' successfully',
    'app.todo.app.todos.remove.error': 'Remove Todo \'{name}\' failed',
    'app.todo.app.todos.create.success': 'Create Todo \'{name}\' successfully',
    'app.todo.app.todos.create.error': 'Create Todo \'{name}\' failed',
    'app.todo.app.todos.update.success': 'Update Todo \'{name}\' successfully',
    'app.todo.app.todos.update.error': 'Update Todo \'{name}\' failed',
    'app.todo.app.todos.empty': 'No Todos',
    'app.todo.app.todos.field.title': 'Todo title',
    'app.todo.app.todos.items.field.name': 'Task Name',
    'app.todo.app.todos.items.field.done': 'Done?',
    'app.todo.app.required': 'This field is required',
    'app.todo.app.field.taken': '\'{field}\' with the same value is already exist',
};
